### ISSUE TITLE
Support for Ruby 1.9.3?

### ISSUE THREAD

**Issue by mdhausman** [tdtds/kindlegen#16]
Hey folks,

What would it take to get this gem working for Ruby 1.9.3? That's the version currently supported under default Ubuntu ppas.

I'd be happy to tackle this myself, but I'm not sure what it is about this project that requires Ruby 2.0.0+.

**Comment by tdtds** [comment]
ruby 1.9.3 was end on Feb 23, 2015. see https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

I cannot support or test kindlgen on ruby 1.9.
