### ISSUE TITLE
cURL   command not  found   

### ISSUE THREAD

**Issue by lzhr** [tdtds/kindlegen#19]
Use the gem on MS Windows， 
can download   curl-7.49.1-win32-mingw.7z
https://curl.haxx.se/download.html#Win32

**Comment by tdtds** [comment]
on installing gem? no. install curl and unzip command before install this gem.

**Comment by mlt** [comment]
So is it the only way to go? Copying curl from msys2 along with some dlls work, but it is kind of a bummer that DevKit on Windows has neither curl nor wget. I didn't look what curl is used for, but can it be rewritten with net/https?

**Comment by dogatana** [comment]
Hi, I made a PR to solve this issue.
Now we don't need make, unzip and curl on Windows.

**Comment by tdtds** [comment]
Hi, kindlegen gem v3.0.0 released. It support Linux, Mac and Windows (without curl or zip commands). Try it please.
