### ISSUE TITLE
How to install "kindlegen"

### ISSUE THREAD

**Issue by glupiowyszlo** [tdtds/kindlegen#28]
I installed Kindle Comic Converter on macOS Sierra. It says "Cannot find KindleGen". Install it using Brew". I guess I installed the Brew by copying the command to Terminal but I got stuck on KindkeGen things. Please be humans and explain it step by step (or link me some tutorials maybe) how to do it to total noob :( Thanks a lot!

**Comment by tdtds** [comment]
This repository is a wrapper of kindlegen command for ruby PROGRAMMER, not for kindlegen USER. I cannot explain how to install kindlegen because I am a Linux user (not MacOS).
