### ISSUE TITLE
Add Windows CI

### ISSUE THREAD

**Issue by slonopotamus** [tdtds/kindlegen#34]
In #32, I discovered that kindlegen doesn't pass tests on Windows because of changes that happened more than a year ago. Instead of manual discovery, it would be much better if kindlegen ran its tests on Windows the same way it runs on Linux. Note however that currently `language: ruby` + `os: windows` is not supported on Travis, even tough their Windows nodes do have Ruby installed.

**Comment by tdtds** [comment]
I agree, but I will be trying to change CI service Travis to Github Actions. Please wait several time.
