### ISSUE TITLE
64-bit native kindlegen executable for Mac

### ISSUE THREAD

**Issue by slonopotamus** [tdtds/kindlegen#36]
See https://github.com/slonopotamus/kindlegen/runs/380905413#step:6:12

```
===============================================================================
Error: test_gem_install(KindlegenTest): Errno::E086: Bad CPU type in executable - /Users/runner/hostedtoolcache/Ruby/2.4.6/x64/lib/ruby/gems/2.4.0/gems/kindlegen-3.0.5/bin/kindlegen
/Users/runner/runners/2.163.1/work/kindlegen/kindlegen/test/test_kindlegen.rb:21:in ``'
/Users/runner/runners/2.163.1/work/kindlegen/kindlegen/test/test_kindlegen.rb:21:in `test_gem_install'
     18:       end
     19:       require 'kindlegen'
     20:     end
  => 21:     output = %x(#{Kindlegen.command})
     22:     assert output.include?('Amazon')
     23:   ensure
     24:     Gem::Uninstaller.new('kindlegen', :executables => true).uninstall rescue nil
===============================================================================
```

The problem is that modern MacOS (Catalina) doesn't support 32-bit binaries anymore. To make things worse, 64-bit kindlegen is not available on [Amazon Kindlegen webpage](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211).

Internets say [people get 64-bit kindlegen from somewhere](https://www.literatureandlatte.com/forum/viewtopic.php?p=284621#p284621), however I failed to find any download link for it.

**Comment by tdtds** [comment]
Ummm... I wonder Amazon now maintain only Kindle Previewer,  then kindlegen will be deprecated?
OK, I have still opened this issue and watch about status of kindlegen for MacOS.

**Comment by slonopotamus** [comment]
I see two options here - either try contacting Amazon so they publish 64-bit kindlegen binary or download Kindlegen Previewer and extract kindlegen binary from it.

**Comment by tdtds** [comment]
Yes, I agree to your suggestion. But I have no interesting to support 64 bit MacOS. If someone asks to Amazon and resolve this problem, of course I will support.

**Comment by slonopotamus** [comment]
Okay, I've reported this issue to Amazon (actually, to Kindle Direct Publishing support).

**Comment by slonopotamus** [comment]
> Hello,
>
> Thank you for contacting Amazon KDP with the issue of KindleGen tool.
>
> Currently we do not have the feature of 64-bit executable for MacOS. 
> 
> I've already forwarded your feedback to our development team. They are looking for ways to improve our service and maybe able to introduce this feature soon in near future.

Not sure if this mean something, but at least I tried :)

**Comment by tdtds** [comment]
Yeh, that is Amazon Standard Style, I know well.

**Comment by slonopotamus** [comment]
I've contacted Kindle Direct Publising support on kinglegen+Catalina issue. If thereare any updates on this, I'll post to tdtds/kindlegen#36

**Comment by mraible** [comment]
Is there any update on this issue? I'd love to find an alternative to downloading kindlegen and building on macOS (since the 32-bit kindlegen doesn't work). I'm trying to add MOBI support back into https://github.com/mraible/infoq-mini-book.

**Comment by slonopotamus** [comment]
I believe this will never happen.
