### ISSUE TITLE
kindlegen without internet connectivity

### ISSUE THREAD

**Issue by randomswdev** [tdtds/kindlegen#41]
I'm rying to use kindlegen in an environment without internet connectivity. I have gems replicated in a local repository, but kindlegen isntallation fails because it is unable to download binaries from the amazon web site.

Is it posible in the current version?

If not, would it be possible to let the rake file build the download URL reading from an environment variable? This would let me copy the binary into an internal repository and then download from there.

If you think this is acceptable, I could contribute the change through a merge request.

**Comment by tdtds** [comment]
> If not, would it be possible to let the rake file build the download URL reading from an environment variable? This would let me copy the binary into an internal repository and then download from there.

That idea sounds good! Please make a pull request.

**Comment by tdtds** [comment]
This request has supported by version 3.1.0. 
Set a link of your tarball to `KINDLEGEN_TARBALL_URL` environment variable.
