### ISSUE TITLE
KindleGen binaries are no longer available for download

### ISSUE THREAD

**Issue by slonopotamus** [tdtds/kindlegen#42]
1. https://www.amazon.com/gp/feature.html?docId=1000765211 says "KindleGen is no longer available for download."
2. All old download links from http://kindlegen.s3.amazonaws.com now give access denied

Downstream issue: asciidoctor/asciidoctor-epub3#363

Seems like there is nothing that can be done within `kindlegen` gem because KindleGen EULA doesn't allow redistribution.

**Comment by HonkingGoose** [comment]
Can confirm, I'm running into this too when using Travis CI or a local install.

**Comment by tdtds** [comment]
OMG...

The even worse news is that Kindle Previewer doesn't have a Linux binary.

If you've already installed the kindlegem gem, you can salvage the kindlegen tar.gz file from under the ext directory of the extracted gem file. You can use that to make the kindlegen gem rebuildable, but that's as far as you can go.

**Comment by kerolloz** [comment]
same issue here 

https://github.com/kerolloz/api_on_rails/runs/1033959046?check_suite_focus=true
![image](https://user-images.githubusercontent.com/36763164/91368030-4ef0ae80-e808-11ea-824f-d7eacc268a04.png)

**Comment by slonopotamus** [comment]
I don't think this issue will be somehow fixed. `kindlegen` gem is just a thin wrapper to download KindleGen binary. But now there is nothing to download (without EULA violation).

There are higher chances that something will be done in asciidoctor/asciidoctor-epub3#363. asciidoctor-epub3 can use alternative ways to produce Mobi, not only through Kindlegen.

**Comment by amejiarosario** [comment]
I had a workaround to make it work: https://github.com/tdtds/kindlegen/pull/43. Dig to find the missing files and added them to the repo. Now, it works again! 🎉

**Comment by gregturn** [comment]
Whereas Amazon is no longer releasing kindlegen, you can apparently snag an up-to-date binary from Kindle Previewer 3 at inside `/Applications/Kindle Previewer 3.app/Contents/lib/fc/bin`.

Not that I'd advocate going that way.

**Comment by slonopotamus** [comment]
@tdtds while technically you have me permissions to make commits in this repo, I would like you to look at #44. If you agree this is an acceptable way to go, let's merge it and push a new `kindlegen` gem release.
